-- Migration number: 0001 	 2026-08-13T16:42:17.832Z

ALTER TABLE songs ADD COLUMN title TEXT;
ALTER TABLE songs ADD COLUMN cover_base64 TEXT;
ALTER TABLE songs ADD COLUMN description TEXT;
ALTER TABLE songs ADD COLUMN duration INTEGER DEFAULT 0;
ALTER TABLE songs ADD COLUMN pubdate INTEGER DEFAULT 0;
ALTER TABLE songs ADD COLUMN owner_name TEXT;
ALTER TABLE songs ADD COLUMN owner_mid INTEGER;
ALTER TABLE songs ADD COLUMN owner_face TEXT;
ALTER TABLE songs ADD COLUMN stat_view INTEGER DEFAULT 0;
ALTER TABLE songs ADD COLUMN stat_danmaku INTEGER DEFAULT 0;
ALTER TABLE songs ADD COLUMN stat_reply INTEGER DEFAULT 0;
ALTER TABLE songs ADD COLUMN stat_favorite INTEGER DEFAULT 0;
ALTER TABLE songs ADD COLUMN stat_coin INTEGER DEFAULT 0;
ALTER TABLE songs ADD COLUMN stat_share INTEGER DEFAULT 0;
ALTER TABLE songs ADD COLUMN stat_like INTEGER DEFAULT 0;
ALTER TABLE songs ADD COLUMN snapshot_synced_at TIMESTAMP;
